# Generated by Django 5.0.7 on 2024-08-31 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=70)),
                ('employee_email', models.EmailField(max_length=254)),
                ('employee_desgination', models.CharField(max_length=70)),
                ('employee_salary', models.IntegerField()),
            ],
        ),
    ]
