# Generated by Django 5.0.7 on 2024-09-04 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('desgination', models.CharField(max_length=70)),
                ('salary', models.IntegerField()),
            ],
        ),
    ]
