# Generated by Django 5.0.7 on 2024-09-07 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=70)),
                ('emp_email', models.EmailField(max_length=254)),
                ('emp_desgination', models.CharField(max_length=70)),
                ('emp_salary', models.IntegerField()),
            ],
        ),
    ]
